#include "protheus.ch"

/*ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออฑฑ
ฑฑบPrograma  PortSel    บ Autor ณ Carlos Eduardo     บ Data ณ  20/05/2016 บฑฑ
ฑฑอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออฑฑ
ฑฑบDescricao ณ Ponto de entrada para Sele็ใo dos Portais a serem exibidos บฑฑ
ฑฑอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออฑฑ
ฑฑบUso       ณ Protheus 11                                                บฑฑ
ฑฑอออออออออออฯอออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออฑฑ
ฑฑ																		   ฑฑ
ฑฑ 0 - Para exibir todos os portais (Padrใo)							   ฑฑ
ฑฑ																		   ฑฑ
ฑฑ 1 - Para exibir somente o primeiro Portal (RH)  						   ฑฑ
ฑฑ 																		   ฑฑ
ฑฑ 2 - Para exibir somente o segundo Portal (PMS)  						   ฑฑ
ฑฑ 																		   ฑฑ
ฑฑ 3 - Para exibir somente o terceiro Portal (PLS)  					   ฑฑ
ฑฑ 																		   ฑ
ฑฑ 4 - Para exibir somente o quarto Portal (Portal Protheus)			   ฑฑ
ฑฑ 																		   ฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿*/

User Function PortSel()

Local cRet := "1"

Return(cRet)
